version: '3.2'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: postcenter-server
    container_name: postcenter-node-server
    ports:
      - "5000:5000"
    env_file: ./server/.env

    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: postcenter-client
    container_name: postcenter-client
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network


networks:
    app-network:
        driver: bridge